### ISSUE TITLE
New Gem Releases?

### ISSUE THREAD

**Issue by eric1234** [erichmenge/signed_form#30]
I noticed there is a 0.3 and 0.4 version in the repo but neither are on Rubygems.

**Comment by tubbo** [comment]
Only @erichmenge and @Spaceghost have access to push gem releases.

**Comment by erichmenge** [comment]
If anyone else is interested in taking on maintaining/releasing this gem, I'd be happy to consider them.

Perhaps @schuetzm ?

**Comment by Spaceghost** [comment]
I've had troubles getting releases together through testing and publishing. If someone else can get it working properly and can send me the `.gem`, I can push that up.

Development tooling has sucked, I'll give rejiggering it a go and see if that won't rock anyone's boats.

**Comment by nlsrchtr** [comment]
@erichmenge & @Spaceghost, in https://github.com/erichmenge/signed_form/pull/31#issuecomment-364641061 @schuetzm is asking for maintaining this gem. Would be great if he could join the team and give this gem some new love.

By the way: thanks for your awesome work on this!

**Comment by Spaceghost** [comment]
I super support @schuetzm taking over active maintenance, I just
absolutely fell flat on my face multiple days in a row trying to
follow and reuse the tooling for releases, but didn't feel like
ripping out what probably works for others was a good idea for the
project.

I hope someone else has better progress with releases than I've had,
and if they can smooth it over, I'd be a lot more helpful. (I'm
working on a library I hope to include in this gem when I get it more
stable.)
